### PR TITLE
Tribe CRUD almost done!

### PR DESCRIPTION
**Pull request by zahramaslavi**
In this version the Tribe's Index, Create and Delete functionalities are completely done. The Update feature however, is not finished yet.

### CODE REVIEW

**Comment by calderonroberto** [comment]
Thanks for working on this. The code looks great. I'm merging and will give it a run tomorrow. I also just saw your email and will read it carefully tomorrow too.

For the delete security scope. That's a great point. For now it's fine if people delete stuff. It's a prototype and we can lock it later as we see how people use it.

**Comment by calderonroberto** [comment]
It doesn't need to be fixed now, so don't worry on this merge. Prolly the next one. But fyi the button to add tribes on the landing page doesn't work.

**Comment by zahramaslavi** [comment]
Hi Roberto,

Ok, great.

Could you please run the code and try the add tribe button again. It is
actually strange, because it is working for me without any problem. Is it
the small button on the corner that does not load the modal? or is it the
add button on the modal that does not act on click?

The problem I see with the add button is that in the mobile device emulator
the button does not appear on some devices and actually it is because the
page does not fit correctly in them (I have to fix this later). Also after
adding the image the modal disappears and a small black message should
appear in the bottom of the page, confirming the action (this message does
not appear in all devices. I should fix this too). But when you add or
delete a tribe it will update on the page automatically. So please let me
know if each of these does not work correctly.

All my best,
Zahraa

**Comment by calderonroberto** [comment]
yah, doesn't work in this branch. And I don't get any errors. You could debug it by cloning this particular branch. ;)

And it's the first button on the corner, I don't get a modal.

**Comment by zahramaslavi** [comment]
I've sent you another pull request. Please check it out. :)

**Pull request merged**
